{{- if .Values.mongodb.standalone }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orki-mongodb-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongo
{{- end}}
