{{- if .Values.mongodb.standalone }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orki-mongodb-data
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
{{- end}}
