apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus
        isDefault: true
        editable: true
