apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-config-volume
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: grafana-dashboard-volume
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-datasource-volume
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-config-volume
          configMap:
            name: grafana-config
        - name: grafana-dashboard-volume
          configMap:
            name: grafana-dashboard-config
        - name: grafana-datasource-volume
          configMap:
            name: grafana-datasource-config
