apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-pod-reader-binding
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: prometheus-pod-reader
  apiGroup: rbac.authorization.k8s.io
