apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: orki-front-virtual-service
spec:
  gateways:
    - istio-system/gateway-https
  hosts:
    - {{ .Values.front.domain }}
  http:
    - route:
        - destination:
            host: orki-front-service
            port:
              number: 80