apiVersion: v1
kind: ConfigMap
metadata:
  name: orki-front-config
data:
{{- range $key, $value := .Values.frontConfigMapData }}
  {{ $key }}: {{ $value }}
{{- end }}
  SED_ORKI_SERVER_ENDPOINT: https:\/\/{{ .Values.core.domain }}
