apiVersion: apps/v1
kind: Deployment
metadata:
  name: orki-redis-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orki-redis
  template:
    metadata:
      labels:
        app: orki-redis
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: redis
        image: redis
        imagePullPolicy: Always

        resources:
          requests:
            cpu: 100m

