apiVersion: apps/v1
kind: Deployment
metadata:
  name: orki-worker-deploy
spec:
  selector:
    matchLabels:
      app: orki-worker
  template:
    metadata:
      labels:
        app: orki-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7777"
        prometheus.io/path: "/metrics"
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: worker
        image: "{{ .Values.imageBack.repository }}:{{ .Values.imageBack.tag }}"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /core-docker/liveness
            port: 7777
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
          failureThreshold: 5
        
        readinessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          successThreshold: 2
          timeoutSeconds: 5
          failureThreshold: 1
          httpGet:
            path: /core-docker/liveness
            port: 7777
            scheme: HTTP
              
        resources:
          requests:
            cpu: 100m
            memory: 300Mi

        envFrom:
        - configMapRef:
            name: orki-back-config
        - secretRef:
            name: orki-back-secret
        
        env:
        - name: PROJECT_URL
          value: http://orki-core-service
        - name: AMQP_HOST
          value: "orki-rabbitmq-service"
        - name: REDIS_HOST
          value: "orki-redis-service"
        - name: MQTT_HOST
          value: "orki-mqtt-service"
        - name: BROSERLESS_ENDPOINT
          value: "ws://orki-browserless-service:3000"

        - name: ENV
          value: "production"
        - name: NODE_ENV
          value: "production"

        - name: ORKI_SCHEDULES
          value: ""
        - name: ORKI_QUEUES
          value: ""
        - name: WAIT_FOR_HOSTS
          value: "orki-redis-service:6379;orki-rabbitmq-service:5672;orki-mqtt-service:1883"
        - name: CORE_RUNTIME_MODULE_PATH
          value: "{{ .Values.nfs.bundlePath }}"
        - name: CORE_RUNTIME_LOCAL_MODULE
          value: "{{ not .Values.nfs.enabled }}"
        
{{- if .Values.nfs.enabled }}
        volumeMounts:
        - name: orki-runtime-bundle
          mountPath: {{ .Values.nfs.bundlePath }}
{{- end }}

{{- if .Values.nfs.enabled }}
      volumes:
      - name: orki-runtime-bundle
        persistentVolumeClaim:
          claimName: orki-runtime-bundle-pvc
{{- end }}
