apiVersion: apps/v1
kind: Deployment
metadata:
  name: orki-worker-deploy
spec:
  selector:
    matchLabels:
      app: orki-worker
  template:
    metadata:
      labels:
        app: orki-worker
    spec:
      containers:
      - name: worker
        image: "{{ .Values.imageBack.repository }}:{{ .Values.imageBack.tag }}"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /core-docker/liveness?livenessProbe
            port: 7777
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /core-docker/liveness?readinessProbe
            port: 7777
            scheme: HTTP
              
        resources:
          requests:
            cpu: 100m
            memory: 300Mi

        envFrom:
        - configMapRef:
            name: orki-back-config
        - secretRef:
            name: orki-back-secret
        
        env:
        - name: PROJECT_URL
          value: http://orki-core-service
        - name: AMQP_HOST
          value: "orki-rabbitmq-service"
        - name: REDIS_HOST
          value: "orki-redis-service"
        - name: MQTT_HOST
          value: "orki-mqtt-service"
        - name: BROSERLESS_ENDPOINT
          value: "ws://orki-browserless-service:3000"

        - name: ENV
          value: "production"
        - name: NODE_ENV
          value: "production"

        - name: ORKI_SCHEDULES
          value: ""
        - name: ORKI_QUEUES
          value: ""
        - name: WAIT_FOR_HOSTS
          value: "orki-redis-service:6379;orki-rabbitmq-service:5672;orki-mqtt-service:1883"

