apiVersion: apps/v1
kind: Deployment
metadata:
  name: orki-browserless-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orki-browserless
  template:
    metadata:
      labels:
        app: orki-browserless
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: browserless
        image: browserless/chrome
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          failureThreshold: 3
          initialDelaySeconds: 5
                  
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          failureThreshold: 3
          initialDelaySeconds: 5

        resources:
          requests:
            cpu: 100m

