apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orki-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orki-worker-deploy
  minReplicas: {{ .Values.worker.minReplicas }}
  maxReplicas: {{ .Values.worker.maxReplicas }}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orki-core-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orki-core-deploy
  minReplicas: {{ .Values.core.minReplicas }}
  maxReplicas: {{ .Values.core.maxReplicas }}
