apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- deployment-browserless.yaml
- deployment-mqtt.yaml
- deployment-rabbitmq.yaml
- deployment-redis.yaml
- deployment-core.yaml
- deployment-worker.yaml