{{- if .Values.nfs.enabled }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: orki-runtime-bundle-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orki-runtime-bundle-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""

{{- end }}
